ethereum_rpc = "wss://eth-hoodi.************" # Your Hoodi chain WebSocket RPC
drosera_rpc = "https://relay.devnet.drosera.io"
drosera_address = "0x7E1b5cA35bd6BcAe8Ff33C0dDf79EffCFf0Ad19e"

[traps]

[traps.dormantcontractmonitor]
path = "out/DormantContractTrap.sol/DormantContractTrap.json"
response_contract = "0x0000000000000000000000000000000000000000" # placeholder - using events instead
response_function = "" # empty since we're using event-based alerts
cooldown_period_blocks = 33 # prevent rapid triggers - wait ~4 hours between triggers (assuming 15sec blocks)
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 10
private_trap = false
whitelist = []
address = "0x0000000000000000000000000000000000000000" # placeholder - will be your deployed trap address
